### ISSUE TITLE
BlazorQuill.js throws exception if there isn't a TextEditor component in the view

### ISSUE THREAD

**Issue by aedballs** [somegenericdev/WYSIWYGTextEditor#11]
After saving the HTML from the WYSIWYG component and navigating to a different page/component, I always get this exception

blazor.server.js:1 [2022-07-22T22:11:22.341Z] Error: Microsoft.JSInterop.JSException: Cannot read properties of null (reading '__quill')
TypeError: Cannot read properties of null (reading '__quill')
    at Object.loadQuillHTMLContent (https://localhost:7165/_content/WYSIWYGTextEditor/BlazorQuill.js:47:33)
    at https://localhost:7165/_framework/blazor.server.js:1:3501
    at new Promise (<anonymous>)
    at kt.beginInvokeJSFromDotNet (https://localhost:7165/_framework/blazor.server.js:1:3475)
    at https://localhost:7165/_framework/blazor.server.js:1:72054
    at Array.forEach (<anonymous>)
    at kt._invokeClientMethod (https://localhost:7165/_framework/blazor.server.js:1:72040)
    at kt._processIncomingData (https://localhost:7165/_framework/blazor.server.js:1:70082)
    at connection.onreceive (https://localhost:7165/_framework/blazor.server.js:1:64485)
    at o.onmessage (https://localhost:7165/_framework/blazor.server.js:1:48819)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at WYSIWYGTextEditor.TextEditor.LoadHTMLContent(String quillHTMLContent)
   at Test.Web.Areas.Admin.Pages.AddEditArtist.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

How can I make this only run if there is a TextEditor on the page? What am I missing? 

Thanks!

**Comment by aedballs** [comment]
I was able to resolve this issue by forcing Blazor to load the component that I am redirecting to

_navigationManager.NavigateTo("/Some/Url", true);
